server:
    port: 8088


spring:
   datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     username: root
     password: 123456
     url: jdbc:mysql://54.252.226.118:3306/online_shop
#    url: jdbc:mysql://127.0.0.1:3306/online_shop

mybatis:
  mapper-locations: classpath:*.xml



